spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      data-locations: classpath:data-h2.sql

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true


